### ISSUE TITLE
Drag nd drop not working easly

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#39] opened 2023-12-17 23:57 UTC
in the current version of the app, I am not able to pass from the 1st drag and drop questions since I am not able to "drop" the right questions 

Please ensure the logic for the "drag and drops" is working fine and pls test it.

**Comment by Elmerluis0129** [comment] 2023-12-20 07:55
Hello Christian. In order to check it out and fix it I need you to tell me where exactly you're having that problem.

Example: Drag and drop in Module 1, Lesson 2, Page 4/11

The number of pages you can visualize it in the progress bar. So please let me know where exactly the problem is. @lopezbec

**Comment by lopezbec** [comment] 2023-12-20 16:25
Lesson one page 7, the fiat one of the whole sequence of pages/modules, see the image below. I am not able to test the application beyond this point since I am not able to pass that page

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/54818552/af142deb-3911-4f0a-93be-beb38d1ea938)

**Comment by Elmerluis0129** [comment] 2023-12-21 05:20
It's already fixed so; you can check it out later on. Already updated as well. Thanks 

Imma close this so you can reopen just in case there's another bug related. @lopezbec

**Closed as completed by Elmerluis0129** 2023-12-21 05:20 UTC
Labels: Critical
